import { useState } from 'react'
import type { FormEvent } from 'react'
import { Loader2 } from 'lucide-react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { formatTime, formatWallClock } from '@/lib/format'
import { correctRecord } from '@/lib/attendance'
import type { AttendanceRecord } from '@/lib/types'

/**
 * Correcting an attendance record.
 *
 * This is the one place in the system where a time not generated by the
 * server can be stored, and the database will not accept it without a
 * reason — `attendance_correction_needs_reason` and the trigger both
 * refuse. The reason field is therefore required here too, so the
 * person finds out before they lose their typing rather than after.
 *
 * The trigger snapshots what the record said beforehand, so nothing
 * entered here can erase the original.
 */
export function CorrectionDialog({
  record,
  onClose,
}: {
  record: AttendanceRecord
  onClose: (changed: boolean) => void
}) {
  const [clockIn, setClockIn] = useState(toLagosInput(record.clockInAt))
  const [clockOut, setClockOut] = useState(
    record.clockOutAt ? toLagosInput(record.clockOutAt) : '',
  )
  const [reason, setReason] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (submitting) return

    if (reason.trim() === '') {
      setError('A correction needs a reason. It becomes part of the record.')
      return
    }
    if (clockIn === '') {
      setError('A clock-in time is needed.')
      return
    }

    setSubmitting(true)
    setError(null)

    const { error: failed } = await correctRecord({
      recordId: record.id,
      clockInAt: fromLagosInput(clockIn),
      clockOutAt: clockOut === '' ? null : fromLagosInput(clockOut),
      reason,
    })

    setSubmitting(false)

    if (failed) {
      setError(failed)
      return
    }

    onClose(true)
  }

  return (
    <Dialog open onOpenChange={(open) => !open && onClose(false)}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Correct this record</DialogTitle>
          <DialogDescription>
            The original times stay on the record and remain visible beside your correction.
            Your reason is stored with it, and the change is written to the audit log.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} noValidate className="space-y-5">
          {error && (
            <p role="alert" className="text-sm font-medium text-negative">
              {error}
            </p>
          )}

          <p className="rounded-control bg-wash px-3 py-2 text-sm text-body">
            Currently in at{' '}
            <span className="tabular font-medium text-ink">{formatTime(record.clockInAt)}</span>
            {record.clockOutAt && (
              <>
                , out at{' '}
                <span className="tabular font-medium text-ink">
                  {formatTime(record.clockOutAt)}
                </span>
              </>
            )}
            . All times are Lagos time.
          </p>

          <div className="space-y-2">
            <Label htmlFor="correct-in" className="text-ink">
              Clock in
            </Label>
            <Input
              id="correct-in"
              type="datetime-local"
              value={clockIn}
              onChange={(event) => setClockIn(event.target.value)}
              disabled={submitting}
              required
              className="h-11 text-base"
            />
            {/* The picker itself is drawn by the browser in the device's
                locale, so it may well show 24-hour whatever we do. This
                line makes sure that is never the only reading — and it
                catches 08:00 typed for 20:00, which is the mistake this
                dialog is most likely to produce. */}
            <p className="text-sm text-quiet" aria-live="polite">
              {clockIn === '' ? 'No time entered.' : `Reads as ${formatWallClock(clockIn)}`}
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="correct-out" className="text-ink">
              Clock out <span className="font-normal text-quiet">(leave empty if still in)</span>
            </Label>
            <Input
              id="correct-out"
              type="datetime-local"
              value={clockOut}
              onChange={(event) => setClockOut(event.target.value)}
              disabled={submitting}
              className="h-11 text-base"
            />
            <p className="text-sm text-quiet" aria-live="polite">
              {clockOut === ''
                ? 'Left empty — they are still clocked in.'
                : `Reads as ${formatWallClock(clockOut)}`}
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="correct-reason" className="text-ink">
              Reason
            </Label>
            <Input
              id="correct-reason"
              value={reason}
              onChange={(event) => setReason(event.target.value)}
              disabled={submitting}
              required
              placeholder="Forgot to clock out; confirmed with their manager"
              className="h-11 text-base"
            />
            <p className="text-sm text-quiet">
              Required. Say what happened, not just that it was wrong.
            </p>
          </div>

          <DialogFooter className="gap-2 sm:gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => onClose(false)}
              disabled={submitting}
              className="h-11 text-base"
            >
              Cancel
            </Button>
            <Button type="submit" disabled={submitting} className="h-11 text-base">
              {submitting && <Loader2 className="size-4 animate-spin" aria-hidden="true" />}
              Save correction
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

/**
 * An instant, as the YYYY-MM-DDTHH:mm a datetime-local input wants,
 * expressed in Lagos time.
 *
 * `datetime-local` has no timezone of its own — it shows whatever string
 * you give it and hands the same shape back. So the conversion has to be
 * explicit in both directions, or an HR user in Lagos would be editing
 * times silently shifted into whatever zone their laptop is set to.
 */
function toLagosInput(iso: string): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Africa/Lagos',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  }).formatToParts(new Date(iso))

  const get = (type: string) => parts.find((part) => part.type === type)?.value ?? '00'
  return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`
}

/**
 * The reverse. Nigeria is UTC+1 all year and has never observed daylight
 * saving, so the offset can be stated outright rather than guessed at.
 */
function fromLagosInput(value: string): string {
  return new Date(`${value}:00+01:00`).toISOString()
}
