import type { PostgrestError } from '@supabase/supabase-js'
import { supabase } from '@/lib/supabase'
import { personName } from '@/lib/format'
import type { AttendanceRecord, AttendanceSource, WhoIsInRow } from '@/lib/types'

/**
 * Clocking in and out.
 *
 * Rule 8 in one sentence: not one timestamp in this file is generated by
 * the browser. `app.attendance_enforce_server_time()` overwrites
 * clock_in_at on every insert and clock_out_at on every ordinary
 * clock-out with the database's own `now()`, discarding whatever
 * arrived. A device with a wrong clock — or a deliberately changed one —
 * cannot move a single recorded time.
 *
 * The one exception is a correction, which is the only path allowed to
 * store a time the server did not generate, and the database refuses it
 * without a reason.
 *
 * Nothing here calculates lateness, overtime or absence. Those are
 * policy decisions Anthrop has not made (D4), and building the rules
 * before the answers exist means building them twice.
 */

/** The employment a person clocks against. */
export interface ClockableEmployment {
  employmentId: string
  tenantId: string
}

/**
 * Finds the caller's active employment.
 *
 * Returns null for a login with no employee record behind it — an
 * administrator can hold an account before anyone has created their
 * person row, and the clock has nothing to attach to until they do.
 */
export async function getMyEmployment(
  personId: string | null,
): Promise<{ data: ClockableEmployment | null; error: PostgrestError | null }> {
  if (!personId) return { data: null, error: null }

  const { data, error } = await supabase
    .from('employments')
    .select('id, tenant_id')
    .eq('person_id', personId)
    .eq('status', 'active')
    .order('start_date', { ascending: false, nullsFirst: false })
    .limit(1)
    .maybeSingle()

  if (error) return { data: null, error }
  if (!data) return { data: null, error: null }

  return { data: { employmentId: data.id as string, tenantId: data.tenant_id as string }, error: null }
}

interface RecordRow {
  id: string
  clock_in_at: string
  clock_in_source: AttendanceSource
  clock_out_at: string | null
  clock_out_source: AttendanceSource | null
  corrected_at: string | null
  correction_reason: string | null
  original_clock_in_at: string | null
  original_clock_out_at: string | null
}

function toRecord(row: RecordRow): AttendanceRecord {
  return {
    id: row.id,
    clockInAt: row.clock_in_at,
    clockInSource: row.clock_in_source,
    clockOutAt: row.clock_out_at,
    clockOutSource: row.clock_out_source,
    correctedAt: row.corrected_at,
    correctionReason: row.correction_reason,
    originalClockInAt: row.original_clock_in_at,
    originalClockOutAt: row.original_clock_out_at,
  }
}

const RECORD_COLUMNS =
  'id, clock_in_at, clock_in_source, clock_out_at, clock_out_source, corrected_at, correction_reason, original_clock_in_at, original_clock_out_at'

/** The caller's own history, most recent first. */
export async function listMyAttendance(
  employmentId: string,
): Promise<{ data: AttendanceRecord[] | null; error: PostgrestError | null }> {
  const { data, error } = await supabase
    .from('attendance_records')
    .select(RECORD_COLUMNS)
    .eq('employment_id', employmentId)
    .order('clock_in_at', { ascending: false })
    .limit(60)

  if (error) return { data: null, error }
  return { data: (data as unknown as RecordRow[]).map(toRecord), error: null }
}

/** The open record, if this person is currently clocked in. */
export async function getOpenRecord(
  employmentId: string,
): Promise<{ data: AttendanceRecord | null; error: PostgrestError | null }> {
  const { data, error } = await supabase
    .from('attendance_records')
    .select(RECORD_COLUMNS)
    .eq('employment_id', employmentId)
    .is('clock_out_at', null)
    .order('clock_in_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  if (error) return { data: null, error }
  return { data: data ? toRecord(data as unknown as RecordRow) : null, error: null }
}

/**
 * Clock in.
 *
 * Only the employment and tenant are sent. There is no time in this
 * request at all — the trigger stamps `now()` — which is the strongest
 * possible form of rule 8: there is nothing for a bad clock to get
 * wrong.
 */
export async function clockIn(
  employment: ClockableEmployment,
): Promise<{ error: string | null }> {
  const { error } = await supabase.from('attendance_records').insert({
    tenant_id: employment.tenantId,
    employment_id: employment.employmentId,
  })

  if (error) {
    if (error.code === '42501') {
      return { error: 'You do not have an active employment to clock in against.' }
    }
    return { error: 'That clock-in could not be saved. Check your connection and try again.' }
  }
  return { error: null }
}

/**
 * Clock out.
 *
 * The value sent for clock_out_at is a flag, not data: the trigger sees
 * "this was null and is now not null", replaces it with the server's own
 * `now()`, and sets the source. Sending the browser's time would be
 * pointless rather than dangerous — but it is worth knowing that it is
 * pointless, because it is easy to read this and assume the browser's
 * clock ends up in the record. It does not.
 */
export async function clockOut(recordId: string): Promise<{ error: string | null }> {
  const { error } = await supabase
    .from('attendance_records')
    .update({ clock_out_at: new Date().toISOString() })
    .eq('id', recordId)
    .is('clock_out_at', null)

  if (error) {
    return { error: 'That clock-out could not be saved. Check your connection and try again.' }
  }
  return { error: null }
}

/**
 * Who is in today.
 *
 * No role filtering here. Owner and HR see the whole tenant, a Manager
 * sees their own department, and a member of staff sees only themselves
 * — all decided by the policies on attendance_records, proved at Gate 3
 * and re-verified against this database.
 */
export async function listWhoIsInToday(
  sinceIso: string,
): Promise<{ data: WhoIsInRow[] | null; error: PostgrestError | null }> {
  const { data, error } = await supabase
    .from('attendance_records')
    .select(
      `${RECORD_COLUMNS},
       employment:employments(
         id,
         person:people(id, first_name, last_name, preferred_name),
         department:departments(name)
       )`,
    )
    .gte('clock_in_at', sinceIso)
    .order('clock_in_at', { ascending: false })

  if (error) return { data: null, error }

  interface Row extends RecordRow {
    employment: {
      id: string
      person: { id: string; first_name: string; last_name: string; preferred_name: string | null } | null
      department: { name: string } | null
    } | null
  }

  return {
    data: (data as unknown as Row[]).map((row) => ({
      record: toRecord(row),
      employmentId: row.employment?.id ?? '',
      personName: row.employment?.person
        ? personName({
            firstName: row.employment.person.first_name,
            lastName: row.employment.person.last_name,
            preferredName: row.employment.person.preferred_name,
          })
        : null,
      departmentName: row.employment?.department?.name ?? null,
    })),
    error: null,
  }
}

/**
 * Correct a record.
 *
 * This is the only route by which a time not generated by this server
 * reaches the table, and the database refuses it without a reason —
 * `attendance_correction_needs_reason` and the trigger both check. The
 * trigger also snapshots what the record said beforehand, so the
 * original stays visible next to the correction and a second correction
 * does not erase the first.
 */
export async function correctRecord(input: {
  recordId: string
  clockInAt: string
  clockOutAt: string | null
  reason: string
}): Promise<{ error: string | null }> {
  if (input.reason.trim() === '') {
    return { error: 'A correction needs a reason.' }
  }

  const { error } = await supabase
    .from('attendance_records')
    .update({
      clock_in_at: input.clockInAt,
      clock_out_at: input.clockOutAt,
      correction_reason: input.reason.trim(),
    })
    .eq('id', input.recordId)

  if (!error) return { error: null }

  if (error.code === '23514') {
    if (error.message.includes('out_after_in')) {
      return { error: 'The clock-out time cannot be before the clock-in time.' }
    }
    return { error: 'A correction needs a reason.' }
  }
  if (error.code === '42501') {
    return { error: 'Only an Owner or HR can correct an attendance record.' }
  }
  return { error: 'That correction could not be saved. Try again.' }
}
